### ISSUE TITLE
Contact email link isn't a hyperlink; could use a `mailto:`

### ISSUE THREAD

**Issue by davidjpeacock** [tj/tjholowaychuk.com#12]
Just incase you missed this TJ.  If it's working as designed, I apologize for the intrusion.  :-)

**Comment by tj** [comment]
figured that might get me more spam haha

**Comment by davidjpeacock** [comment]
LOL - whoops; I guess I'm guilty of determined spamming since I raised a defect about being unable to spam you... ;-)
